package domain

func init() {
	unshuffledCards = generateUnshuffledCards()
	shapeToLetterMap = make(map[Shape]string)
	shapeToLetterMap[Spades] = "S"
	shapeToLetterMap[Clubs] = "C"
	shapeToLetterMap[Diamonds] = "D"
	shapeToLetterMap[Hearts] = "H"
	rankToLetterMap = make(map[Rank]string)
	rankToLetterMap[Ace] = "A"
	rankToLetterMap[Two] = "2"
	rankToLetterMap[Three] = "3"
	rankToLetterMap[Four] = "4"
	rankToLetterMap[Five] = "5"
	rankToLetterMap[Six] = "6"
	rankToLetterMap[Seven] = "7"
	rankToLetterMap[Eight] = "8"
	rankToLetterMap[Nine] = "9"
	rankToLetterMap[Ten] = "10"
	rankToLetterMap[Jack] = "J"
	rankToLetterMap[Queen] = "Q"
	rankToLetterMap[King] = "K"
	letterToShapeMap = make(map[string]Shape)
	letterToShapeMap["S"] = Spades
	letterToShapeMap["C"] = Clubs
	letterToShapeMap["D"] = Diamonds
	letterToShapeMap["H"] = Hearts
	letterToRankMap = make(map[string]Rank)
	letterToRankMap["A"] = Ace
	letterToRankMap["2"] = Two
	letterToRankMap["3"] = Three
	letterToRankMap["4"] = Four
	letterToRankMap["5"] = Five
	letterToRankMap["6"] = Six
	letterToRankMap["7"] = Seven
	letterToRankMap["8"] = Eight
	letterToRankMap["9"] = Nine
	letterToRankMap["10"] = Ten
	letterToRankMap["J"] = Jack
	letterToRankMap["Q"] = Queen
	letterToRankMap["K"] = King
}
